/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Song = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'audioFile' : IDL.Text,
  'artist' : IDL.Text,
});
export const Playlist = IDL.Record({
  'name' : IDL.Text,
  'songs' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  'addSong' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSongToPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [], []),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(Playlist)], ['query']),
  'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Song = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'audioFile' : IDL.Text,
    'artist' : IDL.Text,
  });
  const Playlist = IDL.Record({
    'name' : IDL.Text,
    'songs' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    'addSong' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSongToPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [], []),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(Playlist)], ['query']),
    'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };